### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by shahzad-anwer** [coldev/ColdevProLayer#1]
Hi!

Is there any documentation available, how to use this tool.

**Comment by Humberto90** [comment]
Hi, I need documentation about how to use this tool. Help me!!!

**Comment by coldev** [comment]
"Testing mod" includes documentation and examples...

**Comment by NamarsahaM** [comment]
I ran your testing example (test_protect_full_project), copied all files from temp/project. Pasted in WAMP server and ran the script, it shows the encrypted codes.

**Comment by Henrychuks25** [comment]
Please how can I license another user?

**Comment by coldev** [comment]
use a example:      test_hardware_register.php


  $hardwareIDprotect=   'replace with your error license key';
