### ISSUE TITLE
Erro Bug

### ISSUE THREAD

**Issue by msxandroid** [coldev/ColdevProLayer#10]
I found a situation I would like to report. I use a framework in which some files have compound extension example: programa.inc.php, for these naming models when compiling and accessing the files ah an error return: nonexistent file. But the same is in place and compiled. You can check and thank you.
A suggestion is in the parameters, it has a multi value variable (array) to be used as data keys to be read and validated by the program. And thank you all

**Comment by coldev** [comment]
thanks 4 report
