### ISSUE TITLE
support for 64bit

### ISSUE THREAD

**Issue by the-liquid-metal** [coldev/ColdevProLayer#3]
as the title suggests.

**Comment by coldev** [comment]
Soon in three / two months ...  with linux / windows version

**Comment by iRbouh** [comment]
Hi, I would like to know if there is any news about the 64bit version :D

**Comment by ahmadbarrin** [comment]
Hello,

Thanks for this great library, I'm using it on many projects.
I'm also really interested for a 64bits version. Please keep us informed.
