### ISSUE TITLE
publish the source code

### ISSUE THREAD

**Issue by the-liquid-metal** [coldev/ColdevProLayer#4]
as the title suggests.

**Comment by richardeth** [comment]
Why? you increase the chance that someone finds a flaw and is able to decode the encrypted files...

**Comment by oleteacher** [comment]
please do not publish the source. only setting everyone using up to reverse engineering.

**Comment by the-liquid-metal** [comment]
Because it is hosted in open place, and people think it is open source. Otherwise they would buy commercial one which is battle tested. Let people read its code. No need to scare. They will help you make it better and secure.
