### ISSUE TITLE
more cryptic output name, location, and content

### ISSUE THREAD

**Issue by the-liquid-metal** [coldev/ColdevProLayer#5]
It seems ColdevProLayer produces output with ".coldev" extension. When i google with ".coldev" keyword, i get precise link pointing to what "coldev" is (https://www.lawebdelprogramador.com/foros/PHP/1554716-ColdevProLayer-Protege-tu-codigo-php.html). I thing this is not good practice. In my opinion, the best way is totally confusing people with very cryptic file name. for example: "41bcd66ca1668609d4ade88c51364c6d6b201d9b" produced by sha1(rand()). You can use any cryptography function available in core php.

Combined with flexible output location, it will give more effective confusion. We can create single large pool of output for entire project. People can't determine where the files come from.

Furthermore, don't leave a trace by putting "ColdevLayer" string and version number in output. If the engine needs keyword, use cryptic string hardcoded as integral part of the engine. Obfuscation is a one-way process from a human point of view. We don't need any identifier in the output, as long as the engine works fine.

The last piece: produce the cryptic identifier with random/semirandom mechanism at C level code. You can use C macro/preprocessor, or a feeder string on a given file produced by another tool, or totally use other tool to modify the the C sources right before compiling it. PHP is able to do this just with **sha1(rand())** and **str_replace()**. This way, every time the output dll produced, it contains different cryptic identifier string.

Why cryptic identifier is not enough so we need random one?
If we name it, for example, with "qwertyuiop", and do it again and again, then people will remember it. By using notepad, and press CTRL+F, then fill the input box with that string, at the end: viola! this is produced by ColdevLayer.

**Comment by coldev** [comment]
Coldev is part from commercial brand ..   free advertising
