### ISSUE TITLE
Hide any information about the obfuscator

### ISSUE THREAD

**Issue by the-liquid-metal** [coldev/ColdevProLayer#6]
As vendors who do not want their code to be exposed, they will hide any information about the obfuscator which they use to minimize the risk. I thing this is not good practice to expose ColdevProLayer in phpinfo(). Assuming that they know what they are using, then any information about "ColdevProLayer" is meaningless.

If some people insist they have to know what the obfuscator is, then provide an API in the form of constant. For example: COLDEVPROLAYER_VERSION.

A better way is provides a companion dll to access the API. Any constants defined in main dll named with cryptic name. The duty of a companion dll is to recognize that cryptic constants. Within the companion, human friendly name API are defined in order to access the const. For example: get_coldevprolayer_version().

To produce a cryptic constant name at C level code, you can use C macro/preprocessor, or a feeder string on a given file produced by another tool, or totally use other tool to modify the the C sources right before compiling its. PHP is able to do this just with **sha1(rand())** and **str_replace()**.

This way, every time the output dll produced, it contains different name, both in main dll and it's companion.

With this way, we can distribute the main dll, but keep the companion with us.

**Comment by coldev** [comment]
Coldev is part from commercial brand ..   free advertising
