### ISSUE TITLE
PHP 7.2 Support

### ISSUE THREAD

**Issue by oleteacher** [coldev/ColdevProLayer#9]
Any chance of PHP 7.2 support?

Not trying to bring old subject back up, but do you think Linux support will ever happen?

Absolutely love using and many teachers also use to protect the tests of student cheating:)

Cheers!

**Comment by oleteacher** [comment]
I think the project is now dead. Was a  good one with lots of potential. Wishing the DEV's best in 2019.

**Comment by coldev** [comment]
ready
